// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQDBrXnnTKuzGrqsfK-AAHtneCw8O_JA',
    appId: '1:444349078953:web:89e9335e6013d8f93bf8b8',
    messagingSenderId: '444349078953',
    projectId: 'reservaciones-4a6ea',
    authDomain: 'reservaciones-4a6ea.firebaseapp.com',
    databaseURL: 'https://reservaciones-4a6ea-default-rtdb.firebaseio.com',
    storageBucket: 'reservaciones-4a6ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqMm_qtddgNO3CiCwTHzGc4d9Bcy85ZLU',
    appId: '1:444349078953:android:a9339910ee8e1e893bf8b8',
    messagingSenderId: '444349078953',
    projectId: 'reservaciones-4a6ea',
    databaseURL: 'https://reservaciones-4a6ea-default-rtdb.firebaseio.com',
    storageBucket: 'reservaciones-4a6ea.appspot.com',
  );
}
